### ISSUE TITLE
[MainDashboard] maindashboard 레이아웃 구현

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#26]
## 💚 어떤 기능인가요?

메인대시보드 레이아웃을 구현합니다.

## ✅ To Dos

- [x] 메인 대시보드 레이아웃
- [x] 사이드시트

**Comment by Yeonseo-Jo** [comment]
좋아요! 
지금 구현하는 사이드시트는 수정 기능 없는, 기본 사이드시트 맞나용?
둘을 구분해서 이슈 파면 좋을것 같아요
아자아자 갓기-!

**Comment by Jun-min2** [comment]
여기서 사이드시트에 대한 전체적인 뷰를 다룬다고 생각하겠습니다! 
연서가 말하는대로
KR 수정하기 와 진척 정도 입력하기 부분은 한번 더 이슈를 나누는 것도 좋을 것 같아요!
