### ISSUE TITLE
[common] 공통 페이지 레이아웃 

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#34]
## 💚 어떤 기능인가요?
header를 모든 페이지에서 보여지기 위한 공통 레이아웃 설정
## ✅ To Dos

- [ ] 공통 레이아웃 만들기

**Comment by eonseok-jeon** [comment]
이게 header만 만드는 건가요? 아니면 모든 공통 컴포넌트 다 만드는 건가요?

**Comment by Jun-min2** [comment]
어제 얘기한 부분에 대해서 제가 이해한 것이 맞다면, 이전 Header 이슈를 따로 팠어서 그걸로 header를 만들고, header나 다른 또 여러 공통 컴포넌트를 적용하는 것을 이곳에서 하려고 생각하고 있습니다!

**Comment by eonseok-jeon** [comment]
오홍 그렇게 분리하는 이유가 있으신지요? 적용까지 같은 이슈에서 해도 될 거 같은디용

**Comment by eonseok-jeon** [comment]
아하아항 이해했습니다! 화이팅~

**Comment by Yeonseo-Jo** [comment]
확인했습니다 화이팅!
