### ISSUE TITLE
[common] 사이드 drawer 영역 구현

### ISSUE THREAD

**Issue by Yeonseo-Jo** [MOONSHOT-Team/MOONSHOT-CLIENT#38]
## 💚 어떤 기능인가요?
왼쪽 사이드에 들어갈 drawer의 전체적인 ui를 구현하고 dnd 기능을 완성시킵니다

## ✅ To Dos

- [ ] drawer 전체 ui 구현
- [ ] drawer에 구현해 놓은 O box 불러오기
- [ ] data mapping 해서 box 리스트 만들기
- [ ] dnd 기능 완성시키기

**Comment by eonseok-jeon** [comment]
굿굿~

**Comment by SooY2** [comment]
좋슴니다!!

**Comment by Yeonseo-Jo** [comment]
@SooY2 여기도 라벨 수정해놓을게요!

**Comment by Jun-min2** [comment]
화이팅~화이팅~!
