### ISSUE TITLE
[AddOkr] OKR 추가 방식 선택 컴포넌트

### ISSUE THREAD

**Issue by Yeonseo-Jo** [MOONSHOT-Team/MOONSHOT-CLIENT#39]
## 💚 어떤 기능인가요?
OKR 추가 페이지의 첫번째 step인 방식 선택 ui를 구현합니다

## ✅ To Dos

- [x] 추가 방식 선택 컴포넌트 생성
- [x] 방식 선택 버튼 구현

**Comment by eonseok-jeon** [comment]
화이팅 입니다~

**Comment by SooY2** [comment]
조아요!

**Comment by Jun-min2** [comment]
오앙 모달창 띄워서 둘 중 하나 고르게 만드는거 좋아용~!
