### ISSUE TITLE
[AddOkr] 직접 설정하기 Q1 컴포넌트 ui 구현

### ISSUE THREAD

**Issue by Yeonseo-Jo** [MOONSHOT-Team/MOONSHOT-CLIENT#40]
## 💚 어떤 기능인가요?
addOkr - 직접 설정하기 플로우의 첫번째 질문 부분 ui를 구현합니다

![Image](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/82c76db5-7195-4378-8657-8b537109b1d9)

## ✅ To Dos

- [ ] 직접 설정하기 q1 ui 구현
- [ ] addOkr 페이지에 컴포넌트 추가
- [ ] 필요한 state addOkr 상위 페이지에서 관리

**Comment by eonseok-jeon** [comment]
화이팅입니다~

**Comment by SooY2** [comment]
요기 프로그래스바도 공통인가여???

**Comment by Yeonseo-Jo** [comment]
@SooY2 넵! 여기는 형태가 유사해서 공통으로 쓰면 어떨까합니다!
