### ISSUE TITLE
[MainDashboard] SideSheet kr 상세보기 UI 구현 

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#44]
## 💚 어떤 기능인가요?
MainDashboard 페이지의 Sidesheet 뷰 구현

## ✅ To Dos

- [x] 전체적인 뷰 구현
- [x] 상태 선택 드롭다운
- [x] 일정 정하기 캘린더로 선택할 수 있게

**Comment by Yeonseo-Jo** [comment]
사이드시트의 윗부분을 구현하는거죠? 좋습니당 -!

**Comment by Jun-min2** [comment]
![image](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/141208877/31504732-390b-493c-8c71-9382b12bdd4c)
이 부분에 해당하면 프로그래스 바도 포함이 된다고 생각하면 될까요?

**Comment by SooY2** [comment]
사진첨부 감삼당 ㅎㅎ 프로그래스바는 공통컴포넌트입니당!! 오빠가 구현 해주면 제가 가져다 쓰는고!!!
