### ISSUE TITLE
[MainDashboard] SideSheet 체크인화면 UI 구현

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#45]
## 💚 어떤 기능인가요?
maindashboard의 sidesheet에서 체크인 레이아웃과 필요한 공통 컴포넌트 UI를 구현합니다
![스크린샷 2024-01-07 07 12 39](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/101343915/ef14ad65-1b6e-4778-96ed-c4dfbb096498)

## ✅ To Dos

- [x] 입력하기, 수정하기 선택에 따라 입력창 다르게 
- [x] 레이아웃 구현
- [x] 체크인 컴포넌트 공통으로 구현

**Comment by Yeonseo-Jo** [comment]
진척정도 입력하기의 뷰와 KR 수정하기 뷰가 많이 달라서 이슈를 분리하는건 어떨까요?

**Comment by Jun-min2** [comment]
아니면 입력창 위주로 하나,
입력, 수정 뷰로 구분해서 하는것도 괜찮을 거 같아요!

**Comment by SooY2** [comment]
오호 그러면 버튼에 따라 다르게 나오는거랑, 입력, 수정 으로 이슈 2개 더 파겠습니다!!

**Comment by SooY2** [comment]
> 오호 그러면 버튼에 따라 다르게 나오는거랑, 입력, 수정 으로 이슈 2개 더 파겠습니다!!

버튼에 따라 뷰 바뀌는 기능과 안의 공통적인 레이아웃과 컴포넌트 제작 이슈 하나,
각 뷰에 공통컴포넌트(입력창) 적용하고 진척정도와 수정부분 추가하는 이슈, 이렇게 두개로 하는거 어떤가요 ?!?!
