### ISSUE TITLE
[MainDashboard] 목표 달성 시 축하하는 모션 화면

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#46]
## 💚 어떤 기능인가요?
목표달성 시 축하하는 모션
## ✅ To Dos

- [ ] 축하모션

**Comment by Yeonseo-Jo** [comment]
요건 아직 미정이죠? 축하 모션 미리 레퍼런스 찾아서 디팀한테 이런것들 개발 가능하다! 먼저 의견 전달해도 좋을것 같아요 화이팅 -!

**Comment by Jun-min2** [comment]
아자아자 갓기 화이팅~!
