### ISSUE TITLE
[AddOkr] previewOKR tree graph 구현

### ISSUE THREAD

**Issue by Yeonseo-Jo** [MOONSHOT-Team/MOONSHOT-CLIENT#47]
## 💚 어떤 기능인가요?
previewOKR 컴포넌트에 들어갈 tree graph의 ui를 구현합니다.

## ✅ To Dos

- [x] tree graph 공통 컴포넌트로 가져와서 사용
- [x] task 추가 가능하도록 구현
- [x] (dnd 기능은 삭제 됨)

**Comment by eonseok-jeon** [comment]
화이팅!!

**Comment by SooY2** [comment]
파이팅팅팅!!!!

**Comment by Jun-min2** [comment]
진짜 tree 누구보다 잘 알게 될 듯! 화이팅!
