### ISSUE TITLE
[MainDashboard] kr 추가 / 삭제

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#50]
## 💚 어떤 기능인가요?

kr 추가하고 삭제하는 뷰 작업

## ✅ To Dos

- [x] 모달 띄우기
- [x] 추가 뷰 
- [x] 삭제 뷰

**Comment by Yeonseo-Jo** [comment]
확인했습니다! 추가 모달이 구조가 꽤 있게 나오면 이슈 분리해도 좋을것 같습니당 요건 디자인 나오는거 보고 판단하기!

**Comment by SooY2** [comment]
넵 !! 조아요
