### ISSUE TITLE
[MainDashboard] SideSheet 체크인 로그 부분 UI 구현

### ISSUE THREAD

**Issue by SooY2** [MOONSHOT-Team/MOONSHOT-CLIENT#51]
## 💚 어떤 기능인가요?
Sidesheet의 체크인 로그 부분을 퍼블리싱 합니다

## ✅ To Dos

- [x] 하나의 체크인 로그 컴포넌트 만들어서 map

**Comment by Yeonseo-Jo** [comment]
확인했습니당 :) 화잇팅

**Comment by Jun-min2** [comment]
모든 okr에 대해 체크인 로그 map으로..! 화이팅팅!
