### ISSUE TITLE
[common] ProgressBar 만들기

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#54]
## 💚 어떤 기능인가요?
Progress-bar 만들기
## ✅ To Dos

- [x]  progress-bar

**Comment by eonseok-jeon** [comment]
화이팅~

**Comment by Yeonseo-Jo** [comment]
아마 공통 컴포넌트로 사용할 부분이 1) 사이드시트의 프로그래스바 2)add-okr 플로우의 프로그래스바 이정도일것 같아요
히스토리, drawer의 프로그래스바는 조금 디자인이 다르게 나온것 같은데
최대한 추상화 해서 공통 컴포넌트를 활용하는 쪽으로 생각하면 좋을것 같습니다 화이팅!
