### ISSUE TITLE
[history] 왼쪽 sideBar 영역구현

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#55]
## 💚 어떤 기능인가요?
왼쪽 sideBar 영역구현
## ✅ To Dos
- [x] 왼쪽 aside ui 구현

**Comment by eonseok-jeon** [comment]
왼쪽 사이드바 라는게 drawer를 말하는 걸까요?

**Comment by Jun-min2** [comment]
![image](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/141208877/cd7c30f2-1abc-4ba7-8bf0-014ecbd37635)
history에서 왼쪽 사이드바가 drawer는 아직 아닌것으로 알고 있습니다!

**Comment by eonseok-jeon** [comment]
아항 좋아유~

**Comment by Yeonseo-Jo** [comment]
태그가 활성화/비활성화 상태 로직이 복잡하게 나온것 같은데 이 부분 주의해서 작업하면 좋을것 같아요!
또 태그 만드는 이슈 파서 태그도 history 뷰에서 쓰이는 공통 컴포넌트로 사용해도 좋을것 같다는 생각도 드네요
화이팅-!

**Comment by Jun-min2** [comment]
history뷰에서 태그랑 연도를 기능 이슈로 하려고 했었는데, history 뷰에서 쓰이는 공통 컴포넌트로 사용한다는게 잘 이해가 안되서 common으로 한다는건가요?
