### ISSUE TITLE
[history] 왼쪽 sideBar 기능 (추가 의논사항)

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#56]
## 💚 어떤 기능인가요?
테마 버튼 - 해당 버튼과 관련된 것 나타내기
연도 - 각 연도에 작성 시, 연도와 갯수 함께 나타내기 ex.(2023(2))
 해당 연도는 0으로 나타내기 ex.(2024(0))
## ✅ To Dos
- [x] 테마 버튼 필터링
- [x] 관련없는 연도 invisable

**Comment by eonseok-jeon** [comment]
화이팅~

**Comment by Yeonseo-Jo** [comment]
잘 정리했네요! 좋습니당~
