### ISSUE TITLE
[history] 드롭다운 UI

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#57]
## 💚 어떤 기능인가요?
history뷰 드롭다운 UI
## ✅ To Dos

- [x] 각 테마별 드롭다운 만들기
- [x] 정렬 UI

**Comment by eonseok-jeon** [comment]
<img width="194" alt="스크린샷 2024-01-06 오후 8 37 56" src="https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/121864459/aa31cec7-a3da-4449-a35c-b77618b09663">
이거 구현하기 맞을까용?

**Comment by Jun-min2** [comment]
이건 order로 따로 이슈 팠습니다! 
![image](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/141208877/d393b78f-8fff-4b16-a96b-ce8f9c842c12)
이걸 보시면 될 것 같아요!

**Comment by eonseok-jeon** [comment]
accordian ui라고 따로 불리는 표현이 있긴 한데 상관은 없을 듯 합니다
화이팅~

**Comment by Yeonseo-Jo** [comment]
확인했습니당 화이팅-!
