### ISSUE TITLE
[history] 히스토리 drawer,dropDown Flow연결

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#58]
## 💚 어떤 기능인가요?

히스토리 드롭다운 order기능
## ✅ To Dos

- [x] 드롭다운 order 기능

**Comment by Jun-min2** [comment]
![image](https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/141208877/9aa3535d-50aa-445c-b7b9-32411c9b2020)
이게 드롭다운 되고 order 기능 되도록 할 것 같아요!

**Comment by eonseok-jeon** [comment]
이거 피그마에 펼쳐졌을 때에 대한 UI는 없는 거 같은데 
한 번 찾아보시고 없으면 디자인 분들에게 요청해 주세요~
화이팅!!

**Comment by Yeonseo-Jo** [comment]
화이팅-!

**Comment by Jun-min2** [comment]
기능명세에는 있는데 최종 GUI에 없어서 요청했습니다!
