### ISSUE TITLE
[my] my view ui 구현

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#59]
## 💚 어떤 기능인가요?
my view ui 구현
## ✅ To Dos

- [ ] my view ui

**Comment by eonseok-jeon** [comment]
UI구현은 UI milstone과 연결시키면 될 거 같아요~
projects status todo로 바꾸는 것도 잊지 마시고요~
화이팅~~

**Comment by Yeonseo-Jo** [comment]
화이팅-!
