### ISSUE TITLE
[social] social 왼쪽 sideBar 영역 및 기능 구현

### ISSUE THREAD

**Issue by Jun-min2** [MOONSHOT-Team/MOONSHOT-CLIENT#60]
## 💚 어떤 기능인가요?
왼쪽 sideBar 기능 구현! social에 대해서 클릭 시 해당 tree구조 보여짐
## ✅ To Dos

- [x] 버튼 클릭 시 해당 tree구조 보여짐

**Comment by eonseok-jeon** [comment]
ㅎㄷㄷ 뷰 짤 거 많네용~
천천히 빠르게 화이팅 해봅시다!!

**Comment by Yeonseo-Jo** [comment]
좋습니당 화이팅!
