### ISSUE TITLE
[common] 글자수 제한 함수 구현

### ISSUE THREAD

**Issue by Yeonseo-Jo** [MOONSHOT-Team/MOONSHOT-CLIENT#78]
## 💚 어떤 기능인가요?
텍스트 필드(input, textarea)에서 쓰일 글자수 제한하는 함수를 구현합니다

## ✅ To Dos

- [x] 글자수 제한해주는 util 함수 만들어서 재사용할수 있도록 추상화
- [x] 이모티콘 이슈 해결

**Comment by SooY2** [comment]
헉 미리 잘 쓸게요💖
